### PR TITLE
Fix panics

### LINKED ISSUE #20: Loading bar broke the functionality of the plus command
@TheRustyPickle Unfortunately, the loading bar broke the functionality of the `plus` command.

If I have a timer `@0` and execute the command `plus 0 10`, the following error occurs:

thread 'main' panicked at 'Ratio should be between 0 and 1 inclusively.', C:\Users\..\.cargo\registry\src\github.com-1ecc6299db9ec823\ratatui-0.21.0\src\widgets\gauge.rs:62:9

### PR DESCRIPTION
**Pull request by TheRustyPickle**
**What changed:**
- Fixed plus minus merge command not working properly with gauge
- Fixed merge causing panic if a non-existing id is typed
- Modified timer u16 to u64 to handle larger numbers without causing panic

Resolves #20. Let me know what you think of it.

### CODE REVIEW

File: src/timer_logic.rs [hunk 1]
```diff
@@ -73,9 +73,25 @@ pub fn merge_timers(argument1: &str, argument2: &str, config: &mut Configuration
...
+                id_1_found = true;
+            }
+            if i.id as usize == id2 {
+                id_2_found = true;
+            }
+        }
+
+        if id_1_found && id_2_found {
+            let t = config.timers.remove(id2);
         config.timers[id].description += &format!(" ({})", t.description);
```
Comment (Jo6a) [inline src/timer_logic.rs]: Indentation missed.

**Review by Jo6a — COMMENTED** [review]
Thanks for making the code more robust.

**Comment by TheRustyPickle** [comment]
@Jo6a I just fixed the formatting issues.
